name: API Server

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:      # Manual trigger
  push:
    branches: [ main ]
    paths: [ 'api/**', 'web/**', 'database/**', 'sources/**' ]

jobs:
  api-server:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data collection and API generation
        run: |
          # Create API directory
          mkdir -p api
          
          # Run the main job to collect data
          echo "Running main job to collect data..."
          python3 main.py || echo "Main job failed, continuing with API data generation..."
          
          # Back-fill recent historical data (last 30 days)
          echo "Back-filling recent historical data..."
          python3 quick_backfill.py $(date -d '30 days ago' +%Y-%m-%d) $(date -d '1 day ago' +%Y-%m-%d) || echo "Back-fill failed, continuing..."
          
          # Generate API data files using our script
          echo "Generating API data files..."
          python3 generate_api_data.py
          
          echo "API data files generated successfully"

      - name: Commit and push API data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add API data files
          git add api/
          
          # Commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🤖 Update API data - $(date)"
            git push
          fi

      - name: Upload API data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: api-data
          path: api/
          retention-days: 30
