name: API Server

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:      # Manual trigger
  push:
    branches: [ main ]
    paths: [ 'api/**', 'web/**', 'database/**', 'sources/**' ]

jobs:
  api-server:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Collect BNR Data
        run: |
          echo "Collecting BNR exchange rates..."
          python3 main.py || echo "Data collection warning (this is OK on weekends)"
          
      - name: Generate API Data Files
        run: |
          echo "Generating API data files..."
          mkdir -p api
          python3 generate_api_data.py
          echo "✅ API data files generated successfully"

      - name: Commit and push API data
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          
          # Add API data files
          git add api/ || echo "No API files to add"
          
          # Commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🤖 Update API data - $(date +%Y-%m-%d)" || echo "Commit skipped"
            git push || echo "Push failed (this is OK)"
          fi

      - name: Upload API data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: api-data
          path: api/
          retention-days: 30
